# alip's jekyll config
# vim: set ft=yaml et ts=2 sts=2 :

# Configuration
permalink: "/:categories/:year/:month/:day/:title/"
markdown: maruku
pygments: true
lsi: false
exclude: [.gitignore, _config.yml, _libraries, Makefile, tidy.log]

# Custom variables
title: "/dev/alip"
url: "http://alip.github.io"
keywords: "Ali Polatel,alip,blog,programming,coding,personal,homepage,chaos,satranç,satranç dersi,şiir,edebiyat,çağrışım,kaos"

# Author information
author:
  name: "Ali Polatel"
  mail: "polatel@gmail.com"
  jid:  "alip@jaim.at"

# Disqus
disqus:
  shortname: "alip"



